AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  loadawsearthfile:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1536
      Timeout: 60
      Role: >-
        arn:aws:iam::414805755179:role/service-role/load-aws-earth-file-role-7g0cnt7y
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
      Environment:
        Variables:
          awsearthurl: 'https://s3.eu-west-2.amazonaws.com/'
          bucketfolder: raw/
          tempfolder: /tmp/
          uploadbucket: awsbigwindllc
      Tags:
        environment: awstakehome
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
